### ISSUE TITLE
Error on 2 YouTube Video IDs

### ISSUE THREAD

**Issue by xnaas** [xenova/chat-replay-downloader#12]
Upon trying to download [DzEbfQI4TPQ](https://www.youtube.com/watch?v=DzEbfQI4TPQ), the vast majority of the chat is captured, and then this happens:

```
[3:34:24] marshallbenn33: eft lets goooo
[3:34:25] BrokeProphet: Need a new team
Traceback (most recent call last):
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 449, in <module>
    args.url, start_time=args.start_time, end_time=args.end_time, message_type=args.message_type)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 403, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 331, in get_youtube_messages
    data = self.__parse_item(item)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 234, in __parse_item
    self.__time_to_seconds(data['time_text']))
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 95, in __time_to_seconds
    return sum(abs(int(x)) * 60 ** i for i, x in enumerate(reversed(time.split(':')))) * (-1 if time[0] == '-' else 1)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 95, in <genexpr>
    return sum(abs(int(x)) * 60 ** i for i, x in enumerate(reversed(time.split(':')))) * (-1 if time[0] == '-' else 1)
ValueError: invalid literal for int() with base 10: '443,856'
```

Unfortunately, no file is output when this happens.

**Comment by xnaas** [comment]
The same happens for [7PPnCOhkxqo](https://www.youtube.com/watch?v=7PPnCOhkxqo) as well:

```
[4:31:21] Crooklynkat: There is no Try! ONLY DO!
[4:31:21] Ras Al Ghul: 2 hours stream max Sadge
Traceback (most recent call last):
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 449, in <module>
    args.url, start_time=args.start_time, end_time=args.end_time, message_type=args.message_type)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 403, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 331, in get_youtube_messages
    data = self.__parse_item(item)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 234, in __parse_item
    self.__time_to_seconds(data['time_text']))
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 95, in __time_to_seconds
    return sum(abs(int(x)) * 60 ** i for i, x in enumerate(reversed(time.split(':')))) * (-1 if time[0] == '-' else 1)
  File "/home/xnaas/youtube2/chat-replay-downloader/chat_replay_downloader.py", line 95, in <genexpr>
    return sum(abs(int(x)) * 60 ** i for i, x in enumerate(reversed(time.split(':')))) * (-1 if time[0] == '-' else 1)
ValueError: invalid literal for int() with base 10: '443,901'
```

**Comment by xenova** [comment]
Oh okay I see what the issue is. It looks like the time somehow has a decimal in it. I will look into it and fix it! 😃 Thanks for the report. I have never come across this, so it's great to have people doing more testing.

**Comment by xenova** [comment]
Or perhaps, it happens at the end of the stream? 
DzEbfQI4TPQ ->  3:34:26
7PPnCOhkxqo -> 4:31:20

And the times at which the error occurs is right then.

**Comment by xnaas** [comment]
> I have never come across this, so it's great to have people doing more testing.

I'll I'm good at is breaking things. 🙂 Thanks for checking it out so quick!

**Comment by xenova** [comment]
Haha this is actually quite funny, but it looks like you found a bug with YouTube itself:

`{'message': {'runs': [{'text': 'goodnight CC'}, {'emoji': {'emojiId': 'UCcJL2ld6kxy_nuV1u7PVQ0g/bEcrX-WdMsOf-gP7-IHgCQ', 'shortcuts': [':_Handshake:', ':Handshake:'], 'searchTerms': ['_Handshake', 'Handshake'], 
'image': {'thumbnails': [{'url': 'https://yt3.ggpht.com/RJK_VjSRisjLssUef0KQs6qIOgc4siYQedNm_siLypKikn8elgyOMOF1FXNTZuf1Qyi68aoY=w24-h24-c-k-nd', 'width': 24, 'height': 24}, {'url': 'https://yt3.ggpht.com/RJK_VjSRisjLssUef0KQs6qIOgc4siYQedNm_siLypKikn8elgyOMOF1FXNTZuf1Qyi68aoY=w48-h48-c-k-nd', 'width': 48, 'height': 48}], 'accessibility': {'accessibilityData': {'label': ':_Handshake:'}}}, 'isCustomEmoji': True}}, {'emoji': {'emojiId': 'UCcJL2ld6kxy_nuV1u7PVQ0g/bEcrX-WdMsOf-gP7-IHgCQ', 'shortcuts': [':_Handshake:', ':Handshake:'], 'searchTerms': ['_Handshake', 'Handshake'], 'image': {'thumbnails': [{'url': 'https://yt3.ggpht.com/RJK_VjSRisjLssUef0KQs6qIOgc4siYQedNm_siLypKikn8elgyOMOF1FXNTZuf1Qyi68aoY=w24-h24-c-k-nd', 'width': 24, 'height': 24}, {'url': 'https://yt3.ggpht.com/RJK_VjSRisjLssUef0KQs6qIOgc4siYQedNm_siLypKikn8elgyOMOF1FXNTZuf1Qyi68aoY=w48-h48-c-k-nd', 'width': 48, 'height': 48}], 'accessibility': {'accessibilityData': {'label': ':_Handshake:'}}}, 'isCustomEmoji': True}}]}, 'authorName': {'simpleText': 'Tim Sundeen'}, 'authorPhoto': {'thumbnails': [{'url': 'https://yt3.ggpht.com/-kf1DH5rafUw/AAAAAAAAAAI/AAAAAAAAAAA/-N6t8-7UosU/s32-c-k-no-mo-rj-c0xffffff/photo.jpg', 'width': 32, 'height': 32}, {'url': 'https://yt3.ggpht.com/-kf1DH5rafUw/AAAAAAAAAAI/AAAAAAAAAAA/-N6t8-7UosU/s64-c-k-no-mo-rj-c0xffffff/photo.jpg', 'width': 64, 'height': 64}]}, 'contextMenuEndpoint': {'commandMetadata': {'webCommandMetadata': {'ignoreNavigation': True}}, 'liveChatItemContextMenuEndpoint': {'params': 'Q2tjS1JRb2FRMHRUYlhGWk5tVnlaWE5EUmxOT1FqZFJiMlF5ZVdkRFYxRVNKME5PYmsxNlVHRmtjbVZ6UTBaVE5WOU5RVzlrVkZkSlMyTm5NVFU1T0RBME5URTFORE01TWhBQUdqZ2FEUW9MTjFCUWJrTlBhR3Q0Y1c4cUp3b1lWVU5qU2t3eWJHUTJhM2g1WDI1MVZqRjFOMUJXVVRCbkVnczNVRkJ1UTA5b2EzaHhieUFCS0FFeUdnb1lWVU5zVDBrNGRGOXpTekJ0TUVrNFIwTjBMV3RQZEVWMw=='}}, 'id': 'CkUKGkNLU21xWTZlcmVzQ0ZTTkI3UW9kMnlnQ1dREidDTm5NelBhZHJlc0NGUzVfTUFvZFRXSUtjZzE1OTgwNDUxNTQzOTI%3D', 'timestampUsec': '1598045154857764', 'authorBadges': [{'liveChatAuthorBadgeRenderer': {'customThumbnail': {'thumbnails': [{'url': 'https://yt3.ggpht.com/G7oUSLXeYZjSVhK-ivCnvX8URpJ6A7eIUZC_L37R7URLteCllArQ_G5QHnXQtjXmBs1dE5ss8g=s16-c-k'}, {'url': 'https://yt3.ggpht.com/G7oUSLXeYZjSVhK-ivCnvX8URpJ6A7eIUZC_L37R7URLteCllArQ_G5QHnXQtjXmBs1dE5ss8g=s32-c-k'}]}, 'tooltip': 'New member', 'accessibility': {'accessibilityData': {'label': 'New member'}}}}], 'authorExternalChannelId': 'UClOI8t_sK0m0I8GCt-kOtEw', 'contextMenuAccessibility': {'accessibilityData': {'label': 'Comment actions'}}, 'timestampText': {'simpleText': '443,901:25:54'}}`

Is what is returned.

The timestamp they say that message was sent,  was "443,901:25:54". Interestingly, this is actually is "1598045154", which is the timestamp value. I.e. the time in seconds after January 1st 1970. (443901*60*60+25*60+54 = 1598045154)

So, I could just ignore the comma and assume it is 443901:25:54, which, although not accurate, is what youtube is storing. In any case, if you need to do something with times, your best bet is to use the timestamp itself.

Let me know if you have any other way of fixing it. In the meantime, i will just remove the comma and parse it pretending to be a valid time.

**Comment by xnaas** [comment]
> looks like you found a bug with YouTube itself

Why am I unsurprised? 😅 

Whatever fix will work is fine. I'm not worried about extreme accuracy or anything. 😛

**Comment by xenova** [comment]
Okay! #e430142 should "fix" it :), let me know it works fine!
The output to `python chat_replay_downloader.py https://www.youtube.com/watch?v=7PPnCOhkxqo -start_time 4:31:20` should be 

```
[4:31:20] MarkOchoa: RAULLLLLLLLLLLLLLLL
[4:31:20] Crooklynkat: There is no Try! ONLY DO!
[4:31:20] Crooklynkat: There is no Try! ONLY DO!
[4:31:21] K J: RAAAAAUUUUUUUUUUULLLLLLLLL
[4:31:21] nocodeNH: Who is the BEST???
[4:31:21] Venus Pz: Raulllllll
[4:31:21] Crooklynkat: There is no Try! ONLY DO!
[4:31:21] Ras Al Ghul: 2 hours stream max Sadge
[443,901:25:54] Tim Sundeen: goodnight CC:_Handshake::_Handshake:
[443,901:25:57] Bhupendra Kashyap: ;;;
[443,901:25:57] Bhupendra Kashyap: ;
[443,901:25:57] Wesley Wyndam-Pryce: Night
[443,901:25:58] Bhupendra Kashyap: ;
```

**Comment by xenova** [comment]
Okay! 84ab04a should "fix" it :), let me know it works fine!
The output to `python chat_replay_downloader.py https://www.youtube.com/watch?v=7PPnCOhkxqo -start_time 4:31:20` should be 

```
[4:31:20] MarkOchoa: RAULLLLLLLLLLLLLLLL
[4:31:20] Crooklynkat: There is no Try! ONLY DO!
[4:31:20] Crooklynkat: There is no Try! ONLY DO!
[4:31:21] K J: RAAAAAUUUUUUUUUUULLLLLLLLL
[4:31:21] nocodeNH: Who is the BEST???
[4:31:21] Venus Pz: Raulllllll
[4:31:21] Crooklynkat: There is no Try! ONLY DO!
[4:31:21] Ras Al Ghul: 2 hours stream max Sadge
[443,901:25:54] Tim Sundeen: goodnight CC:_Handshake::_Handshake:
[443,901:25:57] Bhupendra Kashyap: ;;;
[443,901:25:57] Bhupendra Kashyap: ;
[443,901:25:57] Wesley Wyndam-Pryce: Night
[443,901:25:58] Bhupendra Kashyap: ;
```

**Comment by xnaas** [comment]
Works great. Thanks. :)
