### ISSUE TITLE
[YouTube] Add exception for privated/deleted video.

### ISSUE THREAD

**Issue by MinkiNTN** [xenova/chat-replay-downloader#15]
I have a list of videos that I'm trying to get chat replay for, and I've discovered that if the video is privated, the script will just crash like this:

```python
H:\YouTubeArchive\Test>python chat_replay_downloader.py https://www.youtube.com/watch?v=ijFMXqa-N0c -message_type all -output ijFMXqa-N0c.chat.json
Traceback (most recent call last):
  File "chat_replay_downloader.py", line 449, in <module>
    args.url, start_time=args.start_time, end_time=args.end_time, message_type=args.message_type)
  File "chat_replay_downloader.py", line 403, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type)
  File "chat_replay_downloader.py", line 253, in get_youtube_messages
    continuation_by_title_map = self.__get_initial_youtube_info(video_id)
  File "chat_replay_downloader.py", line 161, in __get_initial_youtube_info
    columns = ytInitialData['contents']['twoColumnWatchNextResults']
KeyError: 'contents'
```

Would it be possible to add an exception to the script so that it would not crash? I'm using a script to basically step through a list of stream IDs and download chat for them one by one, and it would be nice to be able to skip past this without crashing.

**Comment by xenova** [comment]
Yeah sure I can add that! Good idea 👍

**Comment by xenova** [comment]
Let me know if you run into any other issues. 😃

**Comment by MinkiNTN** [comment]
It works great now 👍 Thanks for the great work!
