### ISSUE TITLE
Tracebacks

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#46]
```
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 767, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 711, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 793, in read_chunked
    self._original_response.close()
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 643, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 567, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type, chat_type, callback)
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 410, in get_youtube_messages
    info = self.__get_live_info(continuation)
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 305, in __get_live_info
    return(self.__get_continuation_info(url))
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 309, in __get_continuation_info
    info = self.__session_get_json(url)
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 145, in __session_get_json
    return self.__session_get(url).json()
  File "C:\Users\x\Downloads\Compressed\chat_replay_downloader_test\tester.py", line 141, in __session_get
    return self.session.get(url)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

```
I'm sure 50% of it's because of my slow internet and 50% because of the script. Can you upload a separate version, especially the last one, before "print(html.text)" had to be added? Please.. I'm so done with reporting issues back to back.. I'm trying to save live chat logs everyday and the last version was perfect since there wasn't any tracebacks at all, no matter how bad my internet was.

I really hope that you could do that since this script is always updated via internet, if my assumption isn't wrong. I just don't want anymore issues in the future..

**Comment by xenova** [comment]
>Can you upload a separate version, especially the last one, before "print(html.text)" had to be added? 

You can always download an earlier version from the releases page (https://github.com/xenova/chat-replay-downloader/releases). 

> I'm sure 50% of it's because of my slow internet and 50% because of the script. 
> the last version was perfect since there wasn't any tracebacks at all, no matter how bad my internet was.

If you look at the changes I have made to the code recently, you will notice that I haven't changed anything regarding the extraction. In other words, I have not changed anything which would cause timeouts. The traceback you show above (`ConnectionResetError`) indicates that your internet is to blame.


> I really hope that you could do that since this script is always updated via internet, if my assumption isn't wrong. I just don't want anymore issues in the future..

The script only updates if you actively synchronise the repo (with git), or if you re-download it. Changes I make do not automatically get pushed to everyone who has downloaded it.

**Comment by artiction** [comment]
Alright, but then that's weird. Since I've never done re-downloads.

From prior experiences, the script works fine, but suddenly something like "unable to parse" or some random tracebacks happen without changing my internet configuration (either changing wifis, DNS, or VPNs).
That's why I thought it has to sync every now and then which frustrates me. Then I report the issue and download the new version. This keeps on happening. I'll try to do that, hopefully this helps and will be the last time I bicker about this. Sorry for this..

**Comment by xenova** [comment]
> Alright, but then that's weird. Since I've never done re-downloads.
> 
> From prior experiences, the script works fine, but suddenly something like "unable to parse" or some random tracebacks happen without changing my internet configuration (either changing wifis, DNS, or VPNs).
> That's why I thought it has to sync every now and then which frustrates me. Then I report the issue and download the new version. This keeps on happening. I'll try to do that, hopefully this helps and will be the last time I bicker about this. Sorry for this..

No worries! I heavily appreciate anyone who spends some time of their day reporting a potential bug/error - so, thank you! Like I said above, I am working on a system which automatically restarts after an error like this occurs - and I am trying my best to get it out as soon as possible.
